@WeatherApplication_HostAddress = http://localhost:5135

GET {{WeatherApplication_HostAddress}}/api/countries
Accept: application/json

###

GET {{WeatherApplication_HostAddress}}/api/regions
Accept: application/json

###
